name: 01-1. GitHub Actions Demo
on: 
  workflow_dispatch:
  workflow_call:
 
push:
  branches:
    - main
  paths:
    - 'labs/**'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
